<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class DistrictsTableSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
  	Model::unguard();

		App\District::create(['id' => 102, 'province_id' => 1, 'name_kh' => 'មង្គលបូរី', 'name_en' => 'Mongkol Borei']);
		App\District::create(['id' => 103, 'province_id' => 1, 'name_kh' => 'ភ្នំស្រុក', 'name_en' => 'Phnum Srok']);
		App\District::create(['id' => 104, 'province_id' => 1, 'name_kh' => 'ព្រះនេត្រព្រះ', 'name_en' => 'Preah Netr Preah']);
		App\District::create(['id' => 105, 'province_id' => 1, 'name_kh' => 'អូរជ្រៅ', 'name_en' => 'Ou Chrov']);
		App\District::create(['id' => 106, 'province_id' => 1, 'name_kh' => 'សិរីសោភ័ណ', 'name_en' => 'Serei Saophoan']);
		App\District::create(['id' => 107, 'province_id' => 1, 'name_kh' => 'ថ្មពួក', 'name_en' => 'Thma Puok']);
		App\District::create(['id' => 108, 'province_id' => 1, 'name_kh' => 'ស្វាយចេក', 'name_en' => 'Svay Chek']);
		App\District::create(['id' => 109, 'province_id' => 1, 'name_kh' => 'ម៉ាឡៃ', 'name_en' => 'Malai']);
		App\District::create(['id' => 110, 'province_id' => 1, 'name_kh' => 'ប៉ោយប៉ែត', 'name_en' => 'Paoy Paet']);
		App\District::create(['id' => 201, 'province_id' => 2, 'name_kh' => 'បាណន់', 'name_en' => 'Banan']);
		App\District::create(['id' => 202, 'province_id' => 2, 'name_kh' => 'ថ្មគោល', 'name_en' => 'Thma Koul']);
		App\District::create(['id' => 203, 'province_id' => 2, 'name_kh' => 'បាត់ដំបង', 'name_en' => 'Battambang']);
		App\District::create(['id' => 204, 'province_id' => 2, 'name_kh' => 'បវេល', 'name_en' => 'Bavel']);
		App\District::create(['id' => 205, 'province_id' => 2, 'name_kh' => 'ឯកភ្នំ', 'name_en' => 'Aek Phnum']);
		App\District::create(['id' => 206, 'province_id' => 2, 'name_kh' => 'មោងឫស្សី', 'name_en' => 'Moung Ruessei']);
		App\District::create(['id' => 207, 'province_id' => 2, 'name_kh' => 'រតនមណ្ឌល', 'name_en' => 'Rotonak Mondol']);
		App\District::create(['id' => 208, 'province_id' => 2, 'name_kh' => 'សង្កែ', 'name_en' => 'Sangkae']);
		App\District::create(['id' => 209, 'province_id' => 2, 'name_kh' => 'សំឡូត', 'name_en' => 'Samlout']);
		App\District::create(['id' => 210, 'province_id' => 2, 'name_kh' => 'សំពៅលូន', 'name_en' => 'Sampov Lun']);
		App\District::create(['id' => 211, 'province_id' => 2, 'name_kh' => 'ភ្នំព្រឹក', 'name_en' => 'Phnum Proek']);
		App\District::create(['id' => 212, 'province_id' => 2, 'name_kh' => 'កំរៀង', 'name_en' => 'Kamrieng']);
		App\District::create(['id' => 213, 'province_id' => 2, 'name_kh' => 'គាស់ក្រឡ', 'name_en' => 'Koas Krala']);
		App\District::create(['id' => 214, 'province_id' => 2, 'name_kh' => 'រុក្ខគិរី', 'name_en' => 'Rukh Kiri']);
		App\District::create(['id' => 301, 'province_id' => 3, 'name_kh' => 'បាធាយ', 'name_en' => 'Batheay']);
		App\District::create(['id' => 302, 'province_id' => 3, 'name_kh' => 'ចំការលើ', 'name_en' => 'Chamkar Leu']);
		App\District::create(['id' => 303, 'province_id' => 3, 'name_kh' => 'ជើងព្រៃ', 'name_en' => 'Cheung Prey']);
		App\District::create(['id' => 304, 'province_id' => 3, 'name_kh' => 'តំបែរ', 'name_en' => 'Dambae']);
		App\District::create(['id' => 305, 'province_id' => 3, 'name_kh' => 'កំពង់ចាម', 'name_en' => 'Kampong Cham']);
		App\District::create(['id' => 306, 'province_id' => 3, 'name_kh' => 'កំពង់សៀម', 'name_en' => 'Kampong Siem']);
		App\District::create(['id' => 307, 'province_id' => 3, 'name_kh' => 'កងមាស', 'name_en' => 'Kang Meas']);
		App\District::create(['id' => 308, 'province_id' => 3, 'name_kh' => 'កោះសូទិន', 'name_en' => 'Kaoh Soutin']);
		App\District::create(['id' => 309, 'province_id' => 3, 'name_kh' => 'ក្រូចឆ្មារ', 'name_en' => 'Krouch Chhmar']);
		App\District::create(['id' => 310, 'province_id' => 3, 'name_kh' => 'មេមត់', 'name_en' => 'Memot']);
		App\District::create(['id' => 311, 'province_id' => 3, 'name_kh' => 'អូររាំងឪ', 'name_en' => 'Ou Reang Ov']);
		App\District::create(['id' => 312, 'province_id' => 3, 'name_kh' => 'ពញាក្រែក', 'name_en' => 'Ponhea Kraek']);
		App\District::create(['id' => 313, 'province_id' => 3, 'name_kh' => 'ព្រៃឈរ', 'name_en' => 'Prey Chhor']);
		App\District::create(['id' => 314, 'province_id' => 3, 'name_kh' => 'ស្រីសន្ធរ', 'name_en' => 'Srei Santhor']);
		App\District::create(['id' => 315, 'province_id' => 3, 'name_kh' => 'ស្ទឹងត្រង់', 'name_en' => 'Stueng Trang']);
		App\District::create(['id' => 316, 'province_id' => 3, 'name_kh' => 'ត្បូងឃ្មុំ', 'name_en' => 'Tboung Khmum']);
		App\District::create(['id' => 317, 'province_id' => 3, 'name_kh' => 'សួង', 'name_en' => 'Suong']);
		App\District::create(['id' => 401, 'province_id' => 4, 'name_kh' => 'បរិបូណ៌', 'name_en' => 'Baribour']);
		App\District::create(['id' => 402, 'province_id' => 4, 'name_kh' => 'ជលគីរី', 'name_en' => 'Chol Kiri']);
		App\District::create(['id' => 403, 'province_id' => 4, 'name_kh' => 'កំពង់ឆ្នាំង', 'name_en' => 'Kampong Chhnang']);
		App\District::create(['id' => 404, 'province_id' => 4, 'name_kh' => 'កំពង់លែង', 'name_en' => 'Kampong Leaeng']);
		App\District::create(['id' => 405, 'province_id' => 4, 'name_kh' => 'កំពង់ត្រឡាច', 'name_en' => 'Kampong Tralach']);
		App\District::create(['id' => 406, 'province_id' => 4, 'name_kh' => 'រលាប្អៀរ', 'name_en' => 'Rolea B\'ier']);
		App\District::create(['id' => 407, 'province_id' => 4, 'name_kh' => 'សាមគ្គីមានជ័យ', 'name_en' => 'Sameakki Mean Chey']);
		App\District::create(['id' => 408, 'province_id' => 4, 'name_kh' => 'ទឹកផុស', 'name_en' => 'Tuek Phos']);
		App\District::create(['id' => 501, 'province_id' => 5, 'name_kh' => 'បរសេដ្ឋ', 'name_en' => 'Basedth']);
		App\District::create(['id' => 502, 'province_id' => 5, 'name_kh' => 'ច្បារមន', 'name_en' => 'Chbar Mon']);
		App\District::create(['id' => 503, 'province_id' => 5, 'name_kh' => 'គងពិសី', 'name_en' => 'Kong Pisei']);
		App\District::create(['id' => 504, 'province_id' => 5, 'name_kh' => 'ឱរ៉ាល់', 'name_en' => 'Aoral']);
		App\District::create(['id' => 505, 'province_id' => 5, 'name_kh' => 'ឧដុង្គ', 'name_en' => 'Odongk']);
		App\District::create(['id' => 506, 'province_id' => 5, 'name_kh' => 'ភ្នំស្រួច', 'name_en' => 'Phnum Sruoch']);
		App\District::create(['id' => 507, 'province_id' => 5, 'name_kh' => 'សំរោងទង', 'name_en' => 'Samraong Tong']);
		App\District::create(['id' => 508, 'province_id' => 5, 'name_kh' => 'ថ្ពង', 'name_en' => 'Thpong']);
		App\District::create(['id' => 601, 'province_id' => 6, 'name_kh' => 'បារាយណ៍', 'name_en' => 'Baray']);
		App\District::create(['id' => 602, 'province_id' => 6, 'name_kh' => 'កំពង់ស្វាយ', 'name_en' => 'Kampong Svay']);
		App\District::create(['id' => 603, 'province_id' => 6, 'name_kh' => 'ស្ទឹងសែន', 'name_en' => 'Stueng Saen']);
		App\District::create(['id' => 604, 'province_id' => 6, 'name_kh' => 'ប្រាសាទបល្ល័ង្គ', 'name_en' => 'Prasat Ballangk']);
		App\District::create(['id' => 605, 'province_id' => 6, 'name_kh' => 'ប្រាសាទសំបូរ', 'name_en' => 'Prasat Sambour']);
		App\District::create(['id' => 606, 'province_id' => 6, 'name_kh' => 'សណ្ដាន់', 'name_en' => 'Sandan']);
		App\District::create(['id' => 607, 'province_id' => 6, 'name_kh' => 'សន្ទុក', 'name_en' => 'Santuk']);
		App\District::create(['id' => 608, 'province_id' => 6, 'name_kh' => 'ស្ទោង', 'name_en' => 'Stoung']);
		App\District::create(['id' => 701, 'province_id' => 7, 'name_kh' => 'អង្គរជ័យ', 'name_en' => 'Angkor Chey']);
		App\District::create(['id' => 702, 'province_id' => 7, 'name_kh' => 'បន្ទាយមាស', 'name_en' => 'Banteay Meas']);
		App\District::create(['id' => 703, 'province_id' => 7, 'name_kh' => 'ឈូក', 'name_en' => 'Chhuk']);
		App\District::create(['id' => 704, 'province_id' => 7, 'name_kh' => 'ជុំគិរី', 'name_en' => 'Chum Kiri']);
		App\District::create(['id' => 705, 'province_id' => 7, 'name_kh' => 'ដងទង់', 'name_en' => 'Dang Tong']);
		App\District::create(['id' => 706, 'province_id' => 7, 'name_kh' => 'កំពង់ត្រាច', 'name_en' => 'Kampong Trach']);
		App\District::create(['id' => 707, 'province_id' => 7, 'name_kh' => 'ទឹកឈូ', 'name_en' => 'Tuek Chhou']);
		App\District::create(['id' => 708, 'province_id' => 7, 'name_kh' => 'កំពត', 'name_en' => 'Kampot']);
		App\District::create(['id' => 801, 'province_id' => 8, 'name_kh' => 'កណ្ដាលស្ទឹង', 'name_en' => 'Kandal Stueng']);
		App\District::create(['id' => 802, 'province_id' => 8, 'name_kh' => 'កៀនស្វាយ', 'name_en' => 'Kien Svay']);
		App\District::create(['id' => 803, 'province_id' => 8, 'name_kh' => 'ខ្សាច់កណ្ដាល', 'name_en' => 'Khsach Kandal']);
		App\District::create(['id' => 804, 'province_id' => 8, 'name_kh' => 'កោះធំ', 'name_en' => 'Kaoh Thum']);
		App\District::create(['id' => 805, 'province_id' => 8, 'name_kh' => 'លើកដែក', 'name_en' => 'Leuk Daek']);
		App\District::create(['id' => 806, 'province_id' => 8, 'name_kh' => 'ល្វាឯម', 'name_en' => 'Lvea Aem']);
		App\District::create(['id' => 807, 'province_id' => 8, 'name_kh' => 'មុខកំពូល', 'name_en' => 'Mukh Kampul']);
		App\District::create(['id' => 808, 'province_id' => 8, 'name_kh' => 'អង្គស្នួល', 'name_en' => 'Angk Snuol']);
		App\District::create(['id' => 809, 'province_id' => 8, 'name_kh' => 'ពញាឮ', 'name_en' => 'Ponhea Lueu']);
		App\District::create(['id' => 810, 'province_id' => 8, 'name_kh' => 'ស្អាង', 'name_en' => 'S\'ang']);
		App\District::create(['id' => 811, 'province_id' => 8, 'name_kh' => 'តាខ្មៅ', 'name_en' => 'Ta Khmau']);
		App\District::create(['id' => 901, 'province_id' => 9, 'name_kh' => 'បុទុមសាគរ', 'name_en' => 'Botum Sakor']);
		App\District::create(['id' => 902, 'province_id' => 9, 'name_kh' => 'គិរីសាគរ', 'name_en' => 'Kiri Sakor']);
		App\District::create(['id' => 903, 'province_id' => 9, 'name_kh' => 'កោះកុង', 'name_en' => 'Kaoh Kong']);
		App\District::create(['id' => 904, 'province_id' => 9, 'name_kh' => 'ខេមរភូមិន្ទ', 'name_en' => 'Khemara Phoumin']);
		App\District::create(['id' => 905, 'province_id' => 9, 'name_kh' => 'មណ្ឌលសីមា', 'name_en' => 'Mondol Seima']);
		App\District::create(['id' => 906, 'province_id' => 9, 'name_kh' => 'ស្រែ អំបិល','name_en' => 'Srae Ambel']);
		App\District::create(['id' => 907, 'province_id' => 9, 'name_kh' => 'ថ្មបាំង', 'name_en' => 'Thma Bang']);
		App\District::create(['id' => 1001, 'province_id' => 10, 'name_kh' => 'ឆ្លូង', 'name_en' => 'Chhloung']);
		App\District::create(['id' => 1002, 'province_id' => 10, 'name_kh' => 'ក្រចេះ', 'name_en' => 'Kracheh']);
		App\District::create(['id' => 1003, 'province_id' => 10, 'name_kh' => 'ព្រែកប្រសព្វ', 'name_en' => 'Prek Prasab']);
		App\District::create(['id' => 1004, 'province_id' => 10, 'name_kh' => 'សំបូរ', 'name_en' => 'Sambour']);
		App\District::create(['id' => 1005, 'province_id' => 10, 'name_kh' => 'ស្នួល', 'name_en' => 'Snuol']);
		App\District::create(['id' => 1006, 'province_id' => 10, 'name_kh' => 'ចិត្របុរី', 'name_en' => 'Chetr Borei']);
		App\District::create(['id' => 1101, 'province_id' => 11, 'name_kh' => 'កែវសីមា', 'name_en' => 'Kaev Seima']);
		App\District::create(['id' => 1102, 'province_id' => 11, 'name_kh' => 'កោះញែក', 'name_en' => 'Kaoh Nheaek']);
		App\District::create(['id' => 1103, 'province_id' => 11, 'name_kh' => 'អូររាំង', 'name_en' => 'Ou Reang']);
		App\District::create(['id' => 1104, 'province_id' => 11, 'name_kh' => 'ពេជ្រាដា', 'name_en' => 'Pech Chreada']);
		App\District::create(['id' => 1105, 'province_id' => 11, 'name_kh' => 'សែនមនោរម្យ', 'name_en' => 'Saen Monourom']);
		App\District::create(['id' => 1201, 'province_id' => 12, 'name_kh' => 'ចំការមន', 'name_en' => 'Chamkar Mon']);
		App\District::create(['id' => 1202, 'province_id' => 12, 'name_kh' => 'ដូនពេញ', 'name_en' => 'Doun Penh']);
		App\District::create(['id' => 1203, 'province_id' => 12, 'name_kh' => '៧មករា', 'name_en' => 'Prampir Meakkakra']);
		App\District::create(['id' => 1204, 'province_id' => 12, 'name_kh' => 'ទួលគោក', 'name_en' => 'Tuol Kouk']);
		App\District::create(['id' => 1205, 'province_id' => 12, 'name_kh' => 'ដង្កោ', 'name_en' => 'Dangkao']);
		App\District::create(['id' => 1206, 'province_id' => 12, 'name_kh' => 'មានជ័យ', 'name_en' => 'Mean Chey']);
		App\District::create(['id' => 1207, 'province_id' => 12, 'name_kh' => 'ឫស្សីកែវ', 'name_en' => 'Russey Keo']);
		App\District::create(['id' => 1208, 'province_id' => 12, 'name_kh' => 'សែនសុខ', 'name_en' => 'Saensokh']);
		App\District::create(['id' => 1209, 'province_id' => 12, 'name_kh' => 'ពោធិ៍សែនជ័យ', 'name_en' => 'Pur SenChey']);
		App\District::create(['id' => 1301, 'province_id' => 13, 'name_kh' => 'ជ័យសែន', 'name_en' => 'Chey Saen']);
		App\District::create(['id' => 1302, 'province_id' => 13, 'name_kh' => 'ឆែប', 'name_en' => 'Chhaeb']);
		App\District::create(['id' => 1303, 'province_id' => 13, 'name_kh' => 'ជាំក្សាន្ដ', 'name_en' => 'Choam Ksant']);
		App\District::create(['id' => 1304, 'province_id' => 13, 'name_kh' => 'គូលែន', 'name_en' => 'Kuleaen']);
		App\District::create(['id' => 1305, 'province_id' => 13, 'name_kh' => 'រវៀង', 'name_en' => 'Rovieng']);
		App\District::create(['id' => 1306, 'province_id' => 13, 'name_kh' => 'សង្គមថ្មី', 'name_en' => 'Sangkum Thmei']);
		App\District::create(['id' => 1307, 'province_id' => 13, 'name_kh' => 'ត្បែងមានជ័យ', 'name_en' => 'Tbaeng Mean Chey']);
		App\District::create(['id' => 1308, 'province_id' => 13, 'name_kh' => 'ព្រះវិហារ', 'name_en' => 'Preah Vihear']);
		App\District::create(['id' => 1401, 'province_id' => 14, 'name_kh' => 'បាភ្នំ', 'name_en' => 'Ba Phnum']);
		App\District::create(['id' => 1402, 'province_id' => 14, 'name_kh' => 'កំចាយមារ', 'name_en' => 'Kamchay Mear']);
		App\District::create(['id' => 1403, 'province_id' => 14, 'name_kh' => 'កំពង់ត្របែក', 'name_en' => 'Kampong Trabaek']);
		App\District::create(['id' => 1404, 'province_id' => 14, 'name_kh' => 'កញ្ជ្រៀច', 'name_en' => 'Kanhchriech']);
		App\District::create(['id' => 1405, 'province_id' => 14, 'name_kh' => 'មេសាង', 'name_en' => 'Me Sang']);
		App\District::create(['id' => 1406, 'province_id' => 14, 'name_kh' => 'ពាមជរ', 'name_en' => 'Peam Chor']);
		App\District::create(['id' => 1407, 'province_id' => 14, 'name_kh' => 'ពាមរក៍', 'name_en' => 'Peam Ro']);
		App\District::create(['id' => 1408, 'province_id' => 14, 'name_kh' => 'ពារាំង', 'name_en' => 'Pea Reang']);
		App\District::create(['id' => 1409, 'province_id' => 14, 'name_kh' => 'ព្រះស្ដេច', 'name_en' => 'Preah Sdach']);
		App\District::create(['id' => 1410, 'province_id' => 14, 'name_kh' => 'ព្រៃវែង', 'name_en' => 'Prey Veng']);
		App\District::create(['id' => 1411, 'province_id' => 14, 'name_kh' => 'ពោធិ៍រៀង', 'name_en' => 'Pur Rieng']);
		App\District::create(['id' => 1412, 'province_id' => 14, 'name_kh' => 'ស៊ីធរកណ្ដាល', 'name_en' => 'Sithor Kandal']);
		App\District::create(['id' => 1413, 'province_id' => 14, 'name_kh' => 'ស្វាយអន្ទរ', 'name_en' => 'Svay Antor']);
		App\District::create(['id' => 1501, 'province_id' => 15, 'name_kh' => 'បាកាន', 'name_en' => 'Bakan']);
		App\District::create(['id' => 1502, 'province_id' => 15, 'name_kh' => 'កណ្ដៀង', 'name_en' => 'Kandieng']);
		App\District::create(['id' => 1503, 'province_id' => 15, 'name_kh' => 'ក្រគរ', 'name_en' => 'Krakor']);
		App\District::create(['id' => 1504, 'province_id' => 15, 'name_kh' => 'ភ្នំក្រវ៉ាញ', 'name_en' => 'Phnum Kravanh']);
		App\District::create(['id' => 1505, 'province_id' => 15, 'name_kh' => 'ពោធិ៍សាត់', 'name_en' => 'Pursat']);
		App\District::create(['id' => 1506, 'province_id' => 15, 'name_kh' => 'វាលវែង', 'name_en' => 'Veal Veaeng']);
		App\District::create(['id' => 1601, 'province_id' => 16, 'name_kh' => 'អណ្ដូងមាស', 'name_en' => 'Andoung Meas']);
		App\District::create(['id' => 1602, 'province_id' => 16, 'name_kh' => 'បានលុង', 'name_en' => 'Ban Lung']);
		App\District::create(['id' => 1603, 'province_id' => 16, 'name_kh' => 'បរកែវ', 'name_en' => 'Bar Kaev']);
		App\District::create(['id' => 1604, 'province_id' => 16, 'name_kh' => 'កូនមុំ', 'name_en' => 'Koun Mom']);
		App\District::create(['id' => 1605, 'province_id' => 16, 'name_kh' => 'លំផាត់', 'name_en' => 'Lumphat']);
		App\District::create(['id' => 1606, 'province_id' => 16, 'name_kh' => 'អូរជុំ', 'name_en' => 'Ou Chum']);
		App\District::create(['id' => 1607, 'province_id' => 16, 'name_kh' => 'អូរយ៉ាដាវ', 'name_en' => 'Ou Ya Dav']);
		App\District::create(['id' => 1608, 'province_id' => 16, 'name_kh' => 'តាវែង', 'name_en' => 'Ta Veaeng']);
		App\District::create(['id' => 1609, 'province_id' => 16, 'name_kh' => 'វើនសៃ', 'name_en' => 'Veun Sai']);
		App\District::create(['id' => 1701, 'province_id' => 17, 'name_kh' => 'អង្គរជុំ', 'name_en' => 'Angkor Chum']);
		App\District::create(['id' => 1702, 'province_id' => 17, 'name_kh' => 'អង្គរធំ', 'name_en' => 'Angkor Thum']);
		App\District::create(['id' => 1703, 'province_id' => 17, 'name_kh' => 'បន្ទាយស្រី', 'name_en' => 'Banteay Srei']);
		App\District::create(['id' => 1704, 'province_id' => 17, 'name_kh' => 'ជីក្រែង', 'name_en' => 'Chi Kraeng']);
		App\District::create(['id' => 1706, 'province_id' => 17, 'name_kh' => 'ក្រឡាញ់', 'name_en' => 'Kralanh']);
		App\District::create(['id' => 1707, 'province_id' => 17, 'name_kh' => 'ពួក', 'name_en' => 'Puok']);
		App\District::create(['id' => 1709, 'province_id' => 17, 'name_kh' => 'ប្រាសាទបាគង', 'name_en' => 'Prasat Bakong']);
		App\District::create(['id' => 1710, 'province_id' => 17, 'name_kh' => 'សៀមរាប', 'name_en' => 'Siem Reap']);
		App\District::create(['id' => 1711, 'province_id' => 17, 'name_kh' => 'សូទ្រនិគម', 'name_en' => 'Soutr Nikom']);
		App\District::create(['id' => 1712, 'province_id' => 17, 'name_kh' => 'ស្រីស្នំ', 'name_en' => 'Srei Snam']);
		App\District::create(['id' => 1713, 'province_id' => 17, 'name_kh' => 'ស្វាយលើ', 'name_en' => 'Svay Leu']);
		App\District::create(['id' => 1714, 'province_id' => 17, 'name_kh' => 'វ៉ារិន', 'name_en' => 'Varin']);
		App\District::create(['id' => 1801, 'province_id' => 18, 'name_kh' => 'ព្រះសីហនុ', 'name_en' => 'Preah Sihanouk']);
		App\District::create(['id' => 1802, 'province_id' => 18, 'name_kh' => 'ព្រៃនប់', 'name_en' => 'Prey Nob']);
		App\District::create(['id' => 1803, 'province_id' => 18, 'name_kh' => 'ស្ទឹងហាវ', 'name_en' => 'Stueng Hav']);
		App\District::create(['id' => 1804, 'province_id' => 18, 'name_kh' => 'កំពង់សីលា', 'name_en' => 'Kampong Seila']);
		App\District::create(['id' => 1901, 'province_id' => 19, 'name_kh' => 'សេសាន', 'name_en' => 'Sesan']);
		App\District::create(['id' => 1902, 'province_id' => 19, 'name_kh' => 'សៀមបូក', 'name_en' => 'Siem Bouk']);
		App\District::create(['id' => 1903, 'province_id' => 19, 'name_kh' => 'សៀមប៉ាង', 'name_en' => 'Siem Pang']);
		App\District::create(['id' => 1904, 'province_id' => 19, 'name_kh' => 'ស្ទឹងត្រែង', 'name_en' => 'Stueng Traeng']);
		App\District::create(['id' => 1905, 'province_id' => 19, 'name_kh' => 'ថាឡាបរិវ៉ាត់', 'name_en' => 'Thala Barivat']);
		App\District::create(['id' => 2001, 'province_id' => 20, 'name_kh' => 'ចន្ទ្រា', 'name_en' => 'Chantrea']);
		App\District::create(['id' => 2002, 'province_id' => 20, 'name_kh' => 'កំពង់រោទិ៍', 'name_en' => 'Kampong Rou']);
		App\District::create(['id' => 2003, 'province_id' => 20, 'name_kh' => 'រំដួល', 'name_en' => 'Rumduol']);
		App\District::create(['id' => 2004, 'province_id' => 20, 'name_kh' => 'រមាសហែក', 'name_en' => 'Romeas Haek']);
		App\District::create(['id' => 2005, 'province_id' => 20, 'name_kh' => 'ស្វាយជ្រំ', 'name_en' => 'Svay Chrum']);
		App\District::create(['id' => 2006, 'province_id' => 20, 'name_kh' => 'ស្វាយរៀង', 'name_en' => 'Svay Rieng']);
		App\District::create(['id' => 2007, 'province_id' => 20, 'name_kh' => 'ស្វាយទាប', 'name_en' => 'Svay Teab']);
		App\District::create(['id' => 2008, 'province_id' => 20, 'name_kh' => 'បាវិត', 'name_en' => 'Bavet']);
		App\District::create(['id' => 2101, 'province_id' => 21, 'name_kh' => 'អង្គរបូរី', 'name_en' => 'Angkor Borei']);
		App\District::create(['id' => 2102, 'province_id' => 21, 'name_kh' => 'បាទី', 'name_en' => 'Bati']);
		App\District::create(['id' => 2103, 'province_id' => 21, 'name_kh' => 'បូរីជលសារ', 'name_en' => 'Borei Cholsar']);
		App\District::create(['id' => 2104, 'province_id' => 21, 'name_kh' => 'គីរីវង់', 'name_en' => 'Kiri Vong']);
		App\District::create(['id' => 2105, 'province_id' => 21, 'name_kh' => 'កោះអណ្ដែត', 'name_en' => 'Kaoh Andaet']);
		App\District::create(['id' => 2106, 'province_id' => 21, 'name_kh' => 'ព្រៃកប្បាស', 'name_en' => 'Prey Kabbas']);
		App\District::create(['id' => 2107, 'province_id' => 21, 'name_kh' => 'សំរោង', 'name_en' => 'Samraong']);
		App\District::create(['id' => 2108, 'province_id' => 21, 'name_kh' => 'ដូនកែវ', 'name_en' => 'Doun Kaev']);
		App\District::create(['id' => 2109, 'province_id' => 21, 'name_kh' => 'ត្រាំកក់', 'name_en' => 'Tram Kak']);
		App\District::create(['id' => 2110, 'province_id' => 21, 'name_kh' => 'ទ្រាំង', 'name_en' => 'Treang']);
		App\District::create(['id' => 2201, 'province_id' => 22, 'name_kh' => 'អន្លង់វែង', 'name_en' => 'Anlong Veaeng']);
		App\District::create(['id' => 2202, 'province_id' => 22, 'name_kh' => 'បន្ទាយអំពិល', 'name_en' => 'Banteay Ampil']);
		App\District::create(['id' => 2203, 'province_id' => 22, 'name_kh' => 'ចុងកាល់', 'name_en' => 'Chong Kal']);
		App\District::create(['id' => 2204, 'province_id' => 22, 'name_kh' => 'សំរោង', 'name_en' => 'Samraong']);
		App\District::create(['id' => 2205, 'province_id' => 22, 'name_kh' => 'ត្រពាំងប្រាសាទ', 'name_en' => 'Trapeang Prasat']);
		App\District::create(['id' => 2301, 'province_id' => 23, 'name_kh' => 'ដំណាក់ចង្អើរ', 'name_en' => 'Damnak Chang\'aeur']);
		App\District::create(['id' => 2302, 'province_id' => 23, 'name_kh' => 'កែប', 'name_en' => 'Kaeb']);
		App\District::create(['id' => 2401, 'province_id' => 24, 'name_kh' => 'ប៉ៃលិន', 'name_en' => 'Pailin']);
		App\District::create(['id' => 2402, 'province_id' => 24, 'name_kh' => 'សាលាក្រៅ', 'name_en' => 'Sala Krau']);

  	Model::reguard();
  }
}
